# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-31 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('privacy', models.IntegerField(default=50)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='core.Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_reviewer', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
            ],
        ),
        migrations.CreateModel(
            name='AllReview',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('core.review',),
        ),
        migrations.CreateModel(
            name='FriendsReview',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('core.review',),
        ),
        migrations.CreateModel(
            name='PersonalReview',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('core.review',),
        ),
    ]
