# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(max_length=200, upload_to=b'places')),
                ('caption', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='core.Picture'),
        ),
    ]
