# Generated by Django 2.0 on 2018-03-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
