# Generated by Django 2.0 on 2018-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_place_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='link_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='link_2',
            field=models.URLField(blank=True),
        ),
    ]
