# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-06 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_review_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='privacy',
            field=models.IntegerField(default=50),
        ),
    ]
