# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-06 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='category',
        ),
    ]
