# Generated by Django 2.0 on 2018-03-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveluser',
            name='public_default',
            field=models.BooleanField(default=False),
        ),
    ]
