# Generated by Django 2.0 on 2018-09-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_traveluser_public_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveluser',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='traveluser',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
