# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 12:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_traveluser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveluser',
            name='friends',
            field=models.ManyToManyField(related_name='_traveluser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
