# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-19 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_traveluser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveluser',
            name='friends',
        ),
    ]
