# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-15 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllReview',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('core.review',),
        ),
        migrations.CreateModel(
            name='FriendsReview',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('core.review',),
        ),
        migrations.CreateModel(
            name='PersonalReview',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('core.review',),
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='review',
            name='privacy',
            field=models.IntegerField(default=50),
        ),
    ]
